/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectoftp;

/**
 *
 * @author Windows
 */
public class SeleccionDoble extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionDoble
     */
    public SeleccionDoble() {
        initComponents();
    }
    
    public SeleccionDoble(String config, String yesONo){
        initComponents();
        jLabel1.setText(config);
        botones.add(rbNo);
        botones.add(rbYes);
        if(yesONo.equalsIgnoreCase("Yes")){
            rbYes.setSelected(true);
        }
        else{
            rbNo.setSelected(true);
        }
    }
    public void setJlabelText(String config){
        jLabel1.setText(config);
    }
    public String getJlabelText(){
        String texto= jLabel1.getText();
        return texto;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbYes = new javax.swing.JRadioButton();
        rbNo = new javax.swing.JRadioButton();

        jLabel1.setText("Configuracion");

        botones.add(rbYes);
        rbYes.setText("Yes");

        botones.add(rbNo);
        rbNo.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(rbYes)
                .addGap(18, 18, 18)
                .addComponent(rbNo)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(rbYes)
                .addComponent(rbNo))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbNo;
    private javax.swing.JRadioButton rbYes;
    // End of variables declaration//GEN-END:variables
}
